version: '3.6'

networks:
    mytest:
        name: $DOCKER_NETWORK_NAME

services:
  couchdb:
    image: couchdb:$COUCHDB_VERSION
    container_name: $COUCHDB_CONTAINER_NAME
    environment:
        - COUCHDB_USER=$COUCHDB_ADMIN
        - COUCHDB_PASSWORD=$COUCHDB_PASSWD
    networks:
        - mytest
    ports:
        - $COUCHDB_PORT:$COUCHDB_PORT

  peer:
    image: hyperledger/fabric-peer:$FABRIC_PEER_VERSION
    container_name: $PEER_CONTAINER_NAME
    command: sh -c 'cat /etc/extra_hosts >> /etc/hosts && peer node start'
    restart: unless-stopped
    tty: true
    environment:
        - CORE_PEER_ID=${PEER_CONTAINER_NAME}
        - CORE_PEER_ADDRESS=${PEER_CONTAINER_NAME}:${PEER_PORT}
        - CORE_PEER_LISTENADDRESS=0.0.0.0:${PEER_PORT}
        - CORE_PEER_LOCALMSPID=${ORG_MSPID}
        - CORE_PEER_MSPCONFIGPATH=$FABRIC_CA_CLIENT_HOME/peers/$PEER_NAME/msp
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=$FABRIC_CA_CLIENT_HOME/peers/${PEER_NAME}/tls-msp/signcerts/cert.pem
        - CORE_PEER_TLS_KEY_FILE=$FABRIC_CA_CLIENT_HOME/peers/${PEER_NAME}/tls-msp/keystore/key.pem
        - CORE_PEER_TLS_ROOTCERT_FILE=$FABRIC_CA_CLIENT_HOME/peers/${PEER_NAME}/tls-msp/tlscacerts/tls-ca-cert.pem
        - CORE_PEER_GOSSIP_BOOTSTRAP=${PEER_CONTAINER_NAME}:${PEER_PORT}
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${PEER_CONTAINER_NAME}:${PEER_PORT}
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${PEER_CHAINCODE_PORT}
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - FABRIC_LOGGING_SPEC=INFO
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_PROFILE_ENABLED=true
        - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=$COUCHDB_CONTAINER_NAME:$COUCHDB_PORT
        - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=$COUCHDB_ADMIN
        - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=$COUCHDB_PASSWD
    volumes:
        - $HOST_ETC_HOSTS:/etc/extra_hosts
        - $HOST_VOLUME_CLIENT/peers/${PEER_NAME}:$FABRIC_CA_CLIENT_HOME/peers/${PEER_NAME}
    networks:
        - mytest
    ports:
        - $PEER_PORT:$PEER_PORT
        - $PEER_PORT3:$PEER_PORT3
    depends_on:
        - couchdb

  cli:
    image: hyperledger/fabric-tools:$FABRIC_PEER_VERSION
    container_name: cli
    command: sh -c 'cat /etc/extra_hosts >> /etc/hosts && /bin/bash'
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
        - CORE_PEER_ID=cli
        - CORE_PEER_ADDRESS=${PEER_CONTAINER_NAME}:${PEER_PORT}
        - CORE_PEER_LOCALMSPID=${ORG_MSPID}
        - CORE_PEER_MSPCONFIGPATH=$FABRIC_CA_CLIENT_HOME/peers/$PEER_NAME/msp
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=$FABRIC_CA_CLIENT_HOME/peers/${PEER_NAME}/tls-msp/signcerts/cert.pem
        - CORE_PEER_TLS_KEY_FILE=$FABRIC_CA_CLIENT_HOME/peers/${PEER_NAME}/tls-msp/keystore/key.pem
        - CORE_PEER_TLS_ROOTCERT_FILE=$FABRIC_CA_CLIENT_HOME/peers/${PEER_NAME}/tls-msp/tlscacerts/tls-ca-cert.pem
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - FABRIC_LOGGING_SPEC=INFO
    working_dir: $FABRIC_CA_CLIENT_HOME/cli
    volumes:
        - $HOST_ETC_HOSTS:/etc/extra_hosts
        - $HOST_VOLUME_CLIENT:$FABRIC_CA_CLIENT_HOME/cli
    networks:
        - mytest
