version: '3.6'

networks:
    mytest:
        name: $DOCKER_NETWORK_NAME

services:
  tlsca:
    image: hyperledger/fabric-ca:$FABRIC_CA_VERSION
    container_name: $CA_CONTAINER_NAME
    command: sh -c 'cat /etc/extra_hosts >> /etc/hosts && fabric-ca-server start -d -b $FABRIC_CA_ADMIN:$FABRIC_CA_PASSWD --cfg.affiliations.allowremove --cfg.identities.allowremove --port $FABRIC_CA_PORT'
    environment:
      - FABRIC_CA_HOME=$FABRIC_CA_SERVER_HOME
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=$CA_CSR_CN
      - FABRIC_CA_SERVER_CSR_HOSTS=$CA_CSR_HOSTS
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ../volume/server:$FABRIC_CA_SERVER_HOME
      - ../volume/client:$FABRIC_CA_CLIENT_HOME
      - /etc/hosts:/etc/extra_hosts
    networks:
      - mytest
    ports:
      - $FABRIC_CA_PORT:$FABRIC_CA_PORT
